### ISSUE TITLE
Unable to launch emulator

### ISSUE THREAD

**Issue by omarhassanhub** [ccarcaci/andocker#6]
First of all, thank you for this piece of work. It will solve my issues with having a portable environment. I cloned this repo on my `MAC` and the image seems to have successfully installed but the container is not launching the emulator. 

I logged in to the container and run the following:

![image](https://user-images.githubusercontent.com/55087589/81313314-a31c2b00-907f-11ea-97de-165483d7e98e.png)

I managed to login to the container without running `docker-compose up` and then looked to find out what devices are available but didn't really know where to go from here.

```
docker run -it --entrypoint=/bin/bash 03ea9a09c508
cd platform-tools/
adb devices
List of devices attached
blank
```

I'm new to docker and react/expo so not really sure on how to go about debugging this issue. Any help is appreciated.

**Comment by ccarcaci** [comment]
Let me take a look into it.
I'll be back soon with further information.

**Comment by omarhassanhub** [comment]
Thank you for the prompt response. It is worth mentioning that I'm not using a VM and I'm running this docker image directly from my MAC. 

When I looked through the README file in `docker-android`, it states the following:
`For OSX and Windows OS, please use Virtual Machine that support Virtualization with Ubuntu OS`

Am I supposed to run it in a VM?

Cheers

**Comment by ccarcaci** [comment]
I think so.
Anyway, to be sure please attach here the log of the "emulator" container.

Unfortunately, I don't have the possibility to run the ecosystem in OSX and Windows in the short term.

**Comment by hassao03** [comment]
I've attached the log. When I run `docker-compose up`, I have to manually browse chrome on `http://localhost:6080` and hit the `send CtrlAltDel` for the execution to proceed to the next stage. I'm guessing this should be happening automatically.  

[myDockerCompose.log](https://github.com/ccarcaci/andocker/files/4600688/myDockerCompose.log)


Yesterday, I downloaded Virtualbox on my MAC running Ubuntu but the execution of the docker file failed at `run wget`. Would you be able to share your VM environment so that I can replicate it and run it on a VM? 

My current VM environment:
VirtualBox 6.1
Ubuntu 20.04 LTS (30GB Disk)
Docker 19.03.8

Cheers

**Comment by omarhassanhub** [comment]
I've attached the log. When I run docker-compose up, I have to manually browse chrome on http://localhost:6080 and hit the send CtrlAltDel for the execution to proceed to the next stage. I'm guessing this should be happening automatically.

MAC (Without VM)
[myDockerCompose.log](https://github.com/ccarcaci/andocker/files/4601033/myDockerCompose.log)


Yesterday, I downloaded Virtualbox on my MAC running Ubuntu but the execution of the docker file failed at run wget. Would you be able to share your VM environment so that I can replicate it and run it on a VM?

My current VM environment: 
VirtualBox 6.1 
Ubuntu 20.04 LTS (30GB Disk)
 Docker 19.03.8

**UPDATE**:
I managed to get past the error on Ubuntu and now when it gets to the phase of running the emulator, the same error occurs. The emulator is not starting up.

Ubuntu(Running on VirtualBox VM which in turn runs on my MAC)
[ubuntu.log](https://github.com/ccarcaci/andocker/files/4601043/ubuntu.log)


Cheers

**Comment by omarhassanhub** [comment]
So I did some research and found the following:

- `docker-android` ONLY works with OS's that have `nested virtualisation` enabled. 
- `VirtualBox` does not support `nested virtualisation`. Hence, my earlier attempts failed.
- Turns out that `VMware fusion` supports `nested virtualisation`. Therefore, I installed it on my `MAC` with `Ubuntu` OS to run Android in docker solution but it is extremely slow to load the app on the emulator.

This detail was not really clear from the README file in this repository or [budtmo/docker-android](https://github.com/budtmo/docker-android)

I hope the article/README files get updated so that people are made aware. 

Cheers

**Comment by ccarcaci** [comment]
Agree with you.
I'll do some reworks today and update the README adding the limitations you've spotted, you did a very good job. Appreciated!

Anyway if you need a basic emulator without installing Android Studio take a look to the project I use for personal needs (https://github.com/ccarcaci/android-emu).
It consists of scripts that install/launch Android emulator (both on Ubuntu and OSX). Fork the project, open the scripts and feel free to modify them.
I use it when I write React Native code in order to view in hot reload mode the changes I do.

The andocker project is meant to be installed as a continuous testing phase in a CI.

**Comment by ccarcaci** [comment]
I've added some considerations in the README that summarize your work.
https://github.com/ccarcaci/andocker#usage-technical-limitations

Thank you

**Comment by omarhassanhub** [comment]
Nice one @ccarcaci I will explore the `android-emu`. I appreciate your efforts and I will keep an eye on how this repo develops as I learned quite alot experimenting with this project. 

Keep up the good work. Cheers.

**Comment by ccarcaci** [comment]
Thank you for your interest.
